wallpaper {
    monitor = DP-2
    path = ~/.config/backgrounds/shaded_landscape.png
    fit_mode = cover
}
wallpaper {
    monitor = HDMI-A-1
    path = ~/.config/backgrounds/shaded_landscape.png
    fit_mode = cover
}
